
name: "typedoc"

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install Node
        uses: actions/setup-node@v4
        with:
            node-version: '18'
      - 
        name: Generate Docs
        run: npm install && npm run docs
      -
        name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: api
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
